name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        image_name="ghcr.io/pschichtel/s3-backup:${GITHUB_REF##*/}"
        s3fs_version="1.93"
        restic_version="0.16.0"
        podman build --build-arg S3FS_VERSION="$s3fs_version" --build-arg RESTIC_VERSION="$restic_version" -t "$image_name" .
        podman push "$image_name"
